server:
  port: 8763

spring:
  application:
    name: eurekaserver
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


# spring.application.name and server.port are set in the main methods,
# so not done here
#spring:
#  sleuth:
#    traceId128: true
#    sampler:
#      probability: 1.0
# Adds trace and span IDs to logs (when a trace is in progress)
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#  pattern:
#    level: [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n